$(".padrone").click(
  function(){
    $(".open").toggle().removeClass("open")
    $(this).children().toggle().addClass("open");
  }
)
$(".fa-bars").click(
  function(){
    $('.hamburger-menu').addClass("fadeIn");
  }
)
$(".fa-times").click(
  function(){
    $('.hamburger-menu').removeClass("fadeIn");
  }
)
$(".allarga").click(
  function(){
    $(".open").toggle().removeClass("open")
    $(this).children().slideToggle().addClass("open");
  }
)
